---
  - name: copy script
    copy:
      src: splunk-forwarder.sh
      dest: /tmp/splunk-forwarder.sh
      mode: 0700

  - name: run script
    command: bash /tmp/splunk-forwarder.sh
    register: motdOutput

